### ISSUE TITLE
Autocompletion for component properties

### ISSUE THREAD

**Issue by t-sauer** [ember-tooling/ember-language-server#38]
- autocompletion for properties of built in components like `link-to`, `input` or `textarea`
- autocompletion for own components (probably needs some discussion as what to provide, maybe if a property is marked as public in JSDoc?)

**Comment by lifeart** [comment]
![image](https://user-images.githubusercontent.com/1360552/52015990-66649a00-24f4-11e9-9bab-d26a22687a19.png)

https://github.com/lifeart/ember-component-info/issues/1
