### ISSUE TITLE
Add debugging instructions for testing in real projects

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-tooling/ember-language-server#409]
the DEBUGGING.md covers the basics and the relationship with vscode-ember, 
but the tests are within small projects.

For reproducing real issues in projects, it'd be good to explain how to best compile the vsix, and then install it for local testing.

(I'm still working this out, something has gone wrong currently... script execution order might matter 🤔 )

**Comment by NullVoxPopuli** [comment]
oh it looks like you follow the instructions and just open whatever folder -- I was thinking about this backwards? maybe? How can I be sure the LS I'm using is the local one, and not the published copy?

**Comment by NullVoxPopuli** [comment]
hm, "Client + Server" doesn't hit any of my breakpoints in the server.

**Comment by lifeart** [comment]
@NullVoxPopuli here is logic for loading debugging bundles: https://github.com/ember-tooling/vscode-ember/blob/master/server.js#L3

**Comment by NullVoxPopuli** [comment]
Thank you!
